package qa.automation.page.tests.tcases;

import org.testng.annotations.Test;
import qa.automation.page.tests.base.BaseTest;

public class FourWheelerTestCases extends BaseTest {


    @Test(priority = 1,groups = { "regression" })
    public void verifyCopmPlanForHondaCityPetrolExiWithRelianceAfterJuly2018() {
        //Regestration after july 2018
        openAllApp();
        searchApp("Ice Insurance");
        launchIceApp();
        isIceHomePageDisplayed();
        clickOnQuote();
        waitFor(2);
        selectCarInsu();
        clickOnSuggestplan();
        enterCustomerName("Mohan Rao");
        clickOnNext();
        waitFor(3);
        selectHondaCityPetrolExi();
        selectTownCity();
        SelectRegistrationDate(7);
        waitFor(3);
        clickOnNext();
        selectNoExpiry();
        selectNcb();
        waitFor(2);
        scroll(500,1500 ,500,500);
        selectHDFC();
        select1yearCompre();
        clickOnGeneratesQuote();
        waitFor(5);
        clickOnBuyNow();
        selectTitle();
        enterFirstNamForProposer("Manav");
        enterMidtName("Kumar");
        enterlastNamForProposer("Singh");
        scrollToText("Phone");
        selectDob();
        selectGenderAndMaritalStatus();
        enterEmailId("manav@gmail.com");
        enterphoneNum("6367357113");
        clickOnNext();
        enterCommunicationAddress();
        enterPincode("400001");
        scrollToText("District Name");
        enterState();
        enterCityName();
        enterDistric();
        enterCounty();
        scrollToText("Permanent Address");
        selctSameAsComAddForPerm();
        scrollToText("Registration Address");
        selctSameAsComAddForRegstn();
        waitFor(5);
        clickOnNext();
        enterNomineeName("AbcAny");
        selectDob();
        selectNomineeRelation();
        enterNomineeAdress("Mumbai");
        clickOnNext();
        enterPlateNum("MH-01-SDF-4522");
        selecManufactureDate();
        scrollToText("Vehicle IDV");
        enterChasisNumber("12345678909876543");
        enterEngineNumber("98765432101234567");
        selectVehicleHypoType();
        clickOnNext();
        selectPrevInsurerName();
        selecPolicyExpDate();
        enterPrevPolicyNum("12345");
        clickOnNext();
        scrollToText("Review & Submit");
        clickReviewSubmit();
        clickHomeBtn();
    }

    @Test(priority = 1,groups = { "regression" })
    public void verifyCopmPlanForHondaCityPetrolExiWithRelianceBeforeJuly2018() {
        //Regestration before july 2018
        openAllApp();
        searchApp("Ice Insurance");
        launchIceApp();
        isIceHomePageDisplayed();
        clickOnQuote();
        waitFor(2);
        selectCarInsu();
        clickOnSuggestplan();
        enterCustomerName("Mohan Rao");
        clickOnNext();
        waitFor(3);
        selectHondaCityPetrolExi();
        selectTownCity();
        SelectRegistrationDate(6);
        waitFor(3);
        clickOnNext();
        selectNoExpiry();
        selectNcb();
        waitFor(2);
        scroll(500,1500 ,500,500);
        selectHDFC();
        clickOnGeneratesQuote();
        waitFor(5);
        clickOnBuyNow();
        selectTitle();
        enterFirstNamForProposer("Manav");
        enterMidtName("Kumar");
        enterlastNamForProposer("Singh");
        scrollToText("Phone");
        selectDob();
        selectGenderAndMaritalStatus();
        enterEmailId("manav@gmail.com");
        enterphoneNum("6367357113");
        clickOnNext();
        enterCommunicationAddress();
        enterPincode("400001");
        scrollToText("District Name");
        enterState();
        enterCityName();
        enterDistric();
        enterCounty();
        scrollToText("Permanent Address");
        selctSameAsComAddForPerm();
        scrollToText("Registration Address");
        selctSameAsComAddForRegstn();
        waitFor(5);
        clickOnNext();
        enterNomineeName("AbcAny");
        selectDob();
        selectNomineeRelation();
        enterNomineeAdress("Mumbai");
        clickOnNext();
        enterPlateNum("MH-01-SDF-4522");
        selecManufactureDate();
        scrollToText("Vehicle IDV");
        enterChasisNumber("12345678909876543");
        enterEngineNumber("98765432101234567");
        selectVehicleHypoType();
        clickOnNext();
        selectPrevInsurerName();
        selecPolicyExpDate();
        enterPrevPolicyNum("12345");
        clickOnNext();
        scrollToText("Review & Submit");
        clickReviewSubmit();
        clickHomeBtn();
    }

    @Test(priority = 1,groups = { "regression" })
    public void verifyCopmPlanForHondaCityPetrolExiWithTataAigAfterJuly2018() {
        //Regestration after july 2018
        //verify copmrePlan verifyCopmPlanForWithTataAigAfterJuly2018
        openAllApp();
        searchApp("Ice Insurance");
        launchIceApp();
        isIceHomePageDisplayed();
//        clickOnLeads();
//        clickOnQuoteOnLeadsPage();
        clickOnQuote();
        waitFor(2);
        selectCarInsu();
        clickOnSuggestplan();
        enterCustomerName("Mohan Rao");
        clickOnNext();
        waitFor(3);
        selectHondaCityPetrolExi();
        selectTownCity();
        SelectRegistrationDate(7);
        waitFor(3);
        clickOnNext();
        selectNoExpiry();
        selectNcb();
        waitFor(2);
        scroll(500,1500 ,500,500);
        selectHDFC();
        select1yearCompre();
        clickOnGeneratesQuote();
        waitFor(12);
        clickOnBuyNow();
        clickAgree();
        selecFinancierType();
        selectFinancierName();
        enterFinancierAddress("nearsTajHotel");
        clickOnProceed();
        enterFirstNamForProposer("Manav");
        enterlastNamForProposer("Singh");
        selectDob();
        scrollToText("Single");
        enterEmailId("manav@gmail.com");
        enterphoneNum("6367357113");
        selectGenderAndMaritalStatusForTataAig();
        selectTitleFromDropDown();
        clickOnNext();
        enterAdress("NearHealsRoads");
        enterPincode("400001");
        clickOnNext();
        enterNomineeNameForTataAig("kanchan Gupta");
        enterAge("26");
        selectNomineeRelationForTataAig();
        clickOnNext();
        enterPlateNum("MH-01-SF-4522");
        enterChasisNumber("12345678909876543");
        enterEngineNumber("98765432101234567");
        clickOnNext();
        selectPrevInsurerName();
        enterPrevPolicyNum("12345");
        selectComprehensive();
        selecPolicyExpDate();
        clickOnNext();
        scrollToText("Review & Submit");
        clickReviewSubmit();
        clickHomeBtn();
    }

    @Test(priority = 1,groups = { "regression" })
    public void verifyCopmPlanForHondaCityPetrolExiWithTataAigBeforeJuly2018() {
        //Regestration before july 2018
        openAllApp();
        searchApp("Ice Insurance");
        launchIceApp();
        isIceHomePageDisplayed();
        clickOnQuote();
        waitFor(2);
        selectCarInsu();
        clickOnSuggestplan();
        enterCustomerName("Mohan Rao");
        clickOnNext();
        waitFor(3);
        selectHondaCityPetrolExi();
        selectTownCity();
        SelectRegistrationDate(6);
        waitFor(3);
        clickOnNext();
        selectNoExpiry();
        selectNcb();
        waitFor(2);
        scroll(500,1500 ,500,500);
        selectHDFC();
        clickOnGeneratesQuote();
        waitFor(5);
        clickOnBuyNow();
        selectTitle();
        enterFirstNamForProposer("Manav");
        enterMidtName("Kumar");
        enterlastNamForProposer("Singh");
        scrollToText("Phone");
        selectDob();
        selectGenderAndMaritalStatus();
        enterEmailId("manav@gmail.com");
        enterphoneNum("6367357113");
        clickOnNext();
        enterCommunicationAddress();
        enterPincode("400001");
        scrollToText("District Name");
        enterState();
        enterCityName();
        enterDistric();
        enterCounty();
        scrollToText("Permanent Address");
        selctSameAsComAddForPerm();
        scrollToText("Registration Address");
        selctSameAsComAddForRegstn();
        waitFor(5);
        clickOnNext();
        enterNomineeName("AbcAny");
        selectDob();
        selectNomineeRelation();
        enterNomineeAdress("Mumbai");
        clickOnNext();
        enterPlateNum("MH-01-SDF-4522");
        selecManufactureDate();
        scrollToText("Vehicle IDV");
        enterChasisNumber("12345678909876543");
        enterEngineNumber("98765432101234567");
        selectVehicleHypoType();
        clickOnNext();
        selectPrevInsurerName();
        selecPolicyExpDate();
        enterPrevPolicyNum("12345");
        clickOnNext();
        scrollToText("Review & Submit");
        clickReviewSubmit();
        clickHomeBtn();
    }
}
